/**
 * The designs a page can be published in, with the picture of each.
 *
 * Two surfaces offer them: the start page shows what a page can look like, and
 * the setup asks which one to publish in. Both read this list, so the two cannot
 * come to disagree about which designs exist.
 *
 * They ship with Velvet as bundles, and each is named here beside its picture: a
 * design without a picture cannot be shown whatever a glob found, so the pair is
 * stated once rather than assembled from two lists that can disagree.
 *
 * The manifests are read for the name, the era and the sentence that tells one
 * design from another, so those cannot drift from what the bundle says about
 * itself. The pictures are regenerated by
 * `bun run --cwd site designs:screenshots`, and every one shows a well page:
 * nothing somebody meeting Velvet for the first time sees should be four status
 * pages reporting trouble.
 */

import retroChassisManifest from "../../bundles/retro-chassis/bundle.json";
import ncc1701dManifest from "../../bundles/ncc-1701-d/bundle.json";
import twentyFortyNineManifest from "../../bundles/twenty-forty-nine/bundle.json";
import velvetManifest from "../../bundles/velvet/bundle.json";

import retroChassis from "../assets/designs/retro-chassis.png";
import ncc1701d from "../assets/designs/ncc-1701-d.png";
import twentyFortyNine from "../assets/designs/twenty-forty-nine.png";
import velvet from "../assets/designs/velvet.png";

/** One design, as it is named and pictured wherever it is offered. */
export interface Design {
  /** The bundle directory, which is what a configuration names in `design`. */
  id: string;
  name: string;
  /** The period the design belongs to, where its manifest names one. */
  era: string;
  description: string;
  picture: string;
}

/** As much of a manifest as this reads. */
interface NamedManifest {
  id: string;
  name: string;
  era?: string;
  description: string;
}

/** Each design, in the order they are offered: oldest era last. */
const OFFERED: ReadonlyArray<{ manifest: NamedManifest; picture: string }> = [
  { manifest: velvetManifest, picture: velvet },
  { manifest: retroChassisManifest, picture: retroChassis },
  { manifest: twentyFortyNineManifest, picture: twentyFortyNine },
  { manifest: ncc1701dManifest, picture: ncc1701d },
];

export const DESIGNS: readonly Design[] = OFFERED.map(
  ({ manifest, picture }) => ({
    id: manifest.id,
    name: manifest.name,
    era: manifest.era ?? "",
    description: manifest.description,
    picture,
  }),
);

/**
 * Finds the design a configuration names.
 *
 * @param id - A bundle directory name, as `statusPage.design` carries it.
 * @returns The design, or nothing when no shipped design answers to that name.
 */
export function designById(id: string): Design | undefined {
  return DESIGNS.find((design) => design.id === id);
}
