/// <reference types="vite/client" />

/**
 * The picture of a page published in each theme, as a URL the build resolved.
 *
 * Separate from the catalogue because this is Vite's alone: a picture is an
 * asset the build hashes and rewrites, and the name in the catalogue is what
 * indexes it. The glob is static because a bundler cannot follow a name it only
 * learns at run time.
 *
 * The pictures are regenerated by `bun run --cwd site designs:screenshots`, and
 * every one shows a well page: nothing somebody meeting Velvet for the first
 * time sees should be four status pages reporting trouble.
 */

import type { Theme } from "./themes.js";

const pictures = import.meta.glob("../assets/designs/*.png", {
  eager: true,
  import: "default",
}) as Record<string, string>;

/**
 * The URL a theme's picture is served from.
 *
 * @param theme - The theme, which carries its picture's file name.
 * @returns The URL, or an empty string where the build found no such file.
 */
export function pictureFor(theme: Theme): string {
  return pictures[`../assets/designs/${theme.picture}`] ?? "";
}
