// Generated by scripts/sync-version.mjs. Do not edit by hand.

/**
 * The version Velvet states in its root manifest.
 *
 * Generated rather than read at runtime, because the site is a static build
 * with no repository to read, and written here rather than defined per Vite
 * config, because five separate builds share the header that shows it and
 * stating it five times is the drift `sync-version.mjs` exists to prevent.
 */
export const VELVET_VERSION = "1.5.3";
