import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { DEFAULT_THEME, themeCssVariables } from "../src/lib/theme.js";

/**
 * Writes the values the status page shows before a theme has been applied.
 *
 * `applyTheme` sets every one of these on the document root once `config.json`
 * has been read, and the prerender writes the same set into a `:root` block at
 * build time. Until one of those happens, the page is drawn from whatever the
 * stylesheet says, so the stylesheet is answering the same question and has to
 * give the same answer.
 *
 * Generated rather than written by hand for that reason. Held apart by hand,
 * eight of the seventeen values `app.css` stated had drifted away from what
 * replaced them: `--protocol-ipv4` said `#7c7ef3` against `#6366f1`,
 * `--text-secondary` said `#8b919b` against `#8b8c90`. Nothing reported it,
 * because nothing compared them.
 *
 * The whole set is written rather than the subset `app.css` happened to carry,
 * so there is no list of names to keep in step either.
 *
 * `--cloudy-blobs` is the one value here that cannot be the same as its
 * replacement. Its layout is seeded from the installation's own
 * `owner/repo`, which a build of the generic bundle does not know, so it is
 * generated from an empty seed and every installation replaces it with its own.
 *
 * Usage: bun scripts/write-theme-defaults.ts
 */
const OUTPUT = resolve(
  import.meta.dirname,
  "../src/lib/velvet-theme-defaults.generated.css",
);

const HEADER = `/*
  Generated by scripts/write-theme-defaults.ts. Do not edit by hand.

  What the status page is drawn from until \`applyTheme\` or the prerender
  writes the installation's own theme over it. Every name here is one of those
  two replaces, which is why it is derived from the same resolver they use
  rather than stated a second time.

  \`app.css\` holds the properties that no theme touches, and derives several of
  them from these.
*/
`;

const declarations = Object.entries(themeCssVariables(DEFAULT_THEME, ""))
  .map(([name, value]) => `  ${name}: ${value};`)
  .join("\n");

await writeFile(OUTPUT, `${HEADER}\n:root {\n${declarations}\n}\n`, "utf8");
console.log(`Wrote ${Object.keys(themeCssVariables(DEFAULT_THEME, "")).length} theme defaults.`);
