/**
 * The designs the start page shows, with the picture of each.
 *
 * A page is published in one of these. They ship with Velvet as bundles, and
 * each is named here beside its picture: a design without a picture cannot be
 * shown whatever a glob found, so the pair is stated once rather than assembled
 * from two lists that can disagree.
 *
 * The manifests are read for the name, the era and the sentence that tells one
 * design from another, so those cannot drift from what the bundle says about
 * itself. The pictures are regenerated by
 * `bun run --cwd site designs:screenshots`, and every one shows a well page:
 * nothing somebody meeting Velvet for the first time sees should be four status
 * pages reporting trouble.
 *
 * `site/bundles/proof/` is deliberately absent. It is a bundle like any other
 * and every gate runs over it, but nobody picks it.
 */

import cassetteManifest from "../../bundles/cassette/bundle.json";
import ncc1701dManifest from "../../bundles/ncc-1701-d/bundle.json";
import twentyFortyNineManifest from "../../bundles/twenty-forty-nine/bundle.json";
import velvetManifest from "../../bundles/velvet/bundle.json";

import cassette from "./assets/designs/cassette.png";
import ncc1701d from "./assets/designs/ncc-1701-d.png";
import twentyFortyNine from "./assets/designs/twenty-forty-nine.png";
import velvet from "./assets/designs/velvet.png";

/** One design, as the start page names and pictures it. */
export interface GalleryDesign {
  id: string;
  name: string;
  /** The period the design belongs to, where its manifest names one. */
  era: string;
  description: string;
  picture: string;
}

/** As much of a manifest as this page reads. */
interface NamedManifest {
  id: string;
  name: string;
  era?: string;
  description: string;
}

/** Each design, in the order the start page shows them: oldest era last. */
const OFFERED: ReadonlyArray<{ manifest: NamedManifest; picture: string }> = [
  { manifest: velvetManifest, picture: velvet },
  { manifest: cassetteManifest, picture: cassette },
  { manifest: twentyFortyNineManifest, picture: twentyFortyNine },
  { manifest: ncc1701dManifest, picture: ncc1701d },
];

export const GALLERY_DESIGNS: readonly GalleryDesign[] = OFFERED.map(
  ({ manifest, picture }) => ({
    id: manifest.id,
    name: manifest.name,
    era: manifest.era ?? "",
    description: manifest.description,
    picture,
  }),
);
