/**
 * What a published bundle page runs.
 *
 * Two lines, because everything about which design this is belongs to the build
 * rather than to the page: `virtual:velvet-design` is generated by
 * `site/vite.bundle-page.ts` from the design the installation named, and it is
 * what imports that design's stylesheet and script.
 *
 * The markup is already in the document when this runs, so the script attaches
 * behaviour to what is there rather than building a page.
 */

import { mountDesign } from "virtual:velvet-design";

mountDesign();
