/**
 * What a published theme page runs.
 *
 * Two lines, because everything about which theme this is belongs to the build
 * rather than to the page: `virtual:velvet-theme` is generated by
 * `site/vite.theme-page.ts` from the theme the installation named, and it is
 * what imports that theme's stylesheet and script.
 *
 * The markup is already in the document when this runs, so the script attaches
 * behaviour to what is there rather than building a page.
 */

import { mountTheme } from "virtual:velvet-theme";

mountTheme();
